# Generated by Django 5.1.5 on 2026-09-06 19:35

import apps.common.validators
import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clubs', '0003_alter_teammember_team_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='draft', max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, choices=[('hiking', 'Hiking'), ('trail_running', 'Trail running'), ('cycling', 'Cycling'), ('climbing', 'Climbing'), ('zipline', 'Zipline'), ('skydiving', 'Skydiving'), ('parachuting', 'Parachuting'), ('paragliding', 'Paragliding'), ('hang_gliding', 'Hang gliding'), ('sup_boarding', 'SUP boarding'), ('yachting', 'Yachting'), ('surfing', 'Surfing'), ('kayaking', 'Kayaking'), ('rafting', 'Rafting'), ('canyoneering', 'Canyoneering'), ('wakeboarding', 'Wakeboarding'), ('skiing', 'Skiing'), ('snowboarding', 'Snowboarding'), ('other', 'Other')], max_length=32)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='events/covers/', validators=[apps.common.validators.validate_image_upload])),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('duration_type', models.CharField(choices=[('single', 'Single day'), ('multi', 'Multi-day')], default='single', max_length=16)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('languages', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('en', 'English'), ('hy', 'Armenian'), ('ru', 'Russian')], max_length=8), blank=True, default=list, size=None)),
                ('region', models.CharField(blank=True, choices=[('yerevan', 'Yerevan'), ('aragatsotn', 'Aragatsotn'), ('ararat', 'Ararat'), ('armavir', 'Armavir'), ('gegharkunik', 'Gegharkunik'), ('kotayk', 'Kotayk'), ('lori', 'Lori'), ('shirak', 'Shirak'), ('syunik', 'Syunik'), ('tavush', 'Tavush'), ('vayots_dzor', 'Vayots Dzor')], max_length=32)),
                ('difficulty', models.CharField(blank=True, choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard'), ('extreme', 'Extreme')], max_length=16)),
                ('distance_km', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('elevation_gain_m', models.PositiveIntegerField(blank=True, null=True)),
                ('meeting_point_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('meeting_point_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('meeting_point_url', models.URLField(blank=True)),
                ('meeting_point_note', models.CharField(blank=True, max_length=255)),
                ('required_items', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, default=list, size=None)),
                ('price_type', models.CharField(choices=[('free', 'Free'), ('paid', 'Paid')], default='free', max_length=16)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_participants', models.PositiveIntegerField(blank=True, null=True)),
                ('sold_count', models.PositiveIntegerField(default=0)),
                ('included', models.TextField(blank=True)),
                ('not_included', models.TextField(blank=True)),
                ('cancellation_terms', models.TextField(blank=True)),
                ('other_info', models.TextField(blank=True)),
                ('cancellation_reason', models.CharField(blank=True, choices=[('weather', 'Weather conditions'), ('not_enough_participants', 'Not enough participants'), ('guide_unavailable', 'Guide unavailable'), ('safety', 'Safety concerns'), ('other', 'Other')], max_length=32)),
                ('cancellation_reason_other', models.TextField(blank=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='clubs.club')),
                ('guide', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='guided_events', to='clubs.teammember')),
            ],
            options={
                'ordering': ['-start_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EventGalleryImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='events/gallery/', validators=[apps.common.validators.validate_image_upload])),
                ('order', models.PositiveIntegerField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='events.event')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
