# Generated by Django 5.1.5 on 2026-09-06 16:31

import django.contrib.postgres.fields
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], default='draft', max_length=32)),
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='club', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team_role', models.CharField(blank=True, choices=[('lead_guide', 'Lead guide'), ('sweep_guide', 'Sweep guide'), ('manager', 'Manager'), ('admin_assistant', 'Admin assistant')], max_length=32)),
                ('activity_types', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('hiking', 'Hiking'), ('trail_running', 'Trail running'), ('cycling', 'Cycling'), ('climbing', 'Climbing'), ('zipline', 'Zipline'), ('skydiving', 'Skydiving'), ('parachuting', 'Parachuting'), ('paragliding', 'Paragliding'), ('hang_gliding', 'Hang gliding'), ('sup_boarding', 'SUP boarding'), ('yachting', 'Yachting'), ('surfing', 'Surfing'), ('kayaking', 'Kayaking'), ('rafting', 'Rafting'), ('canyoneering', 'Canyoneering'), ('wakeboarding', 'Wakeboarding'), ('skiing', 'Skiing'), ('snowboarding', 'Snowboarding'), ('other', 'Other')], max_length=32), blank=True, default=list, size=None)),
                ('languages', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('en', 'English'), ('hy', 'Armenian'), ('ru', 'Russian')], max_length=8), blank=True, default=list, size=None)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='team_members/photos/')),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('experience_years', models.PositiveIntegerField(blank=True, null=True)),
                ('bio', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_date', models.DateField(auto_now_add=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to='clubs.club')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='team_membership', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TeamMemberCertificate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file', models.FileField(upload_to='team_members/certificates/')),
                ('team_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='clubs.teammember')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
