# Generated by Django 5.1.5 on 2026-09-06 17:42

import apps.common.storage
import apps.common.validators
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='about',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='club',
            name='activity_types',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('hiking', 'Hiking'), ('trail_running', 'Trail running'), ('cycling', 'Cycling'), ('climbing', 'Climbing'), ('zipline', 'Zipline'), ('skydiving', 'Skydiving'), ('parachuting', 'Parachuting'), ('paragliding', 'Paragliding'), ('hang_gliding', 'Hang gliding'), ('sup_boarding', 'SUP boarding'), ('yachting', 'Yachting'), ('surfing', 'Surfing'), ('kayaking', 'Kayaking'), ('rafting', 'Rafting'), ('canyoneering', 'Canyoneering'), ('wakeboarding', 'Wakeboarding'), ('skiing', 'Skiing'), ('snowboarding', 'Snowboarding'), ('other', 'Other')], max_length=32), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='club',
            name='base_region',
            field=models.CharField(blank=True, choices=[('yerevan', 'Yerevan'), ('aragatsotn', 'Aragatsotn'), ('ararat', 'Ararat'), ('armavir', 'Armavir'), ('gegharkunik', 'Gegharkunik'), ('kotayk', 'Kotayk'), ('lori', 'Lori'), ('shirak', 'Shirak'), ('syunik', 'Syunik'), ('tavush', 'Tavush'), ('vayots_dzor', 'Vayots Dzor')], max_length=32),
        ),
        migrations.AddField(
            model_name='club',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='clubs/covers/', validators=[apps.common.validators.validate_image_upload]),
        ),
        migrations.AddField(
            model_name='club',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='club',
            name='entity_type',
            field=models.CharField(blank=True, choices=[('individual', 'Individual'), ('sole_trader', 'Sole trader'), ('llc', 'LLC'), ('informal', 'Informal group')], max_length=32),
        ),
        migrations.AddField(
            model_name='club',
            name='facebook',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='club',
            name='identity_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='club',
            name='instagram',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='club',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='clubs/logos/', validators=[apps.common.validators.validate_image_upload]),
        ),
        migrations.AddField(
            model_name='club',
            name='owner_id_document',
            field=models.FileField(blank=True, null=True, storage=apps.common.storage.PrivateMediaStorage(), upload_to='clubs/id_documents/', validators=[apps.common.validators.validate_document_upload]),
        ),
        migrations.AddField(
            model_name='club',
            name='payment_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='club',
            name='phone',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='club',
            name='tax_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='club',
            name='telegram',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='club',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='club',
            name='year_founded',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='team_members/photos/', validators=[apps.common.validators.validate_image_upload]),
        ),
        migrations.AlterField(
            model_name='teammembercertificate',
            name='file',
            field=models.FileField(upload_to='team_members/certificates/', validators=[apps.common.validators.validate_document_upload]),
        ),
    ]
