# Generated by Django 5.1.5 on 2026-09-06 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_club_about_club_activity_types_club_base_region_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='team_role',
            field=models.CharField(blank=True, choices=[('manager', 'Manager'), ('admin_assistant', 'Admin assistant')], max_length=32),
        ),
    ]
