# Generated by Django 5.1.5 on 2026-09-25 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0004_remove_teammember_team_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='guided_tour_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
