# Generated by Django 5.1.5 on 2026-08-19 18:33

import django.contrib.postgres.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='custom_capabilities',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('edit_club_profile', 'Edit club profile'), ('create_event', 'Create event'), ('edit_event', 'Edit event'), ('publish_event', 'Publish event'), ('view_participants', 'View participants'), ('export_participants', 'Export participants'), ('qr_check_in', 'QR check-in'), ('confirm_completion', 'Confirm completion'), ('view_finances', 'View finances'), ('manage_team_members', 'Manage team members'), ('cancel_event', 'Cancel event'), ('request_refund', 'Request refund'), ('verify_club', 'Verify club'), ('suspend_club', 'Suspend club'), ('issue_refund', 'Issue refund')], max_length=32), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('participant', 'Participant'), ('club_owner', 'Club Owner'), ('guide', 'Guide'), ('internal_admin', 'Internal Admin'), ('platform_admin', 'Platform Admin')], default='participant', max_length=32),
        ),
    ]
