# Generated by Django 5.1.5 on 2026-09-06 16:31

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_created_by_user_custom_capabilities_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='custom_capabilities',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('edit_club_profile', 'Edit club profile'), ('create_event', 'Create event'), ('edit_event', 'Edit event'), ('publish_event', 'Publish event'), ('view_participants', 'View participants'), ('export_participants', 'Export participants'), ('qr_check_in', 'QR check-in'), ('confirm_completion', 'Confirm completion'), ('view_finances', 'View finances'), ('manage_team_members', 'Manage team members'), ('view_team_members', 'View team members'), ('gps_tracking', 'GPS tracking'), ('emergency_button', 'Emergency button'), ('cancel_event', 'Cancel event'), ('request_refund', 'Request refund'), ('verify_club', 'Verify club'), ('suspend_club', 'Suspend club'), ('issue_refund', 'Issue refund')], max_length=32), blank=True, default=list, size=None),
        ),
    ]
